### ISSUE TITLE
leaders in an array

### ISSUE THREAD

**Issue by Sloth-Panda** [ankitapuri/DSA-guide#216] opened 2021-02-18 16:58 UTC
## 💥 Proposal

(A clear and concise description of what the proposal is.)

finding leaders in an array
### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)

YES

**Comment by Sloth-Panda** [comment] 2021-02-18 16:59
@ankitapuri would like to work on it using python/c++

**Comment by kanak22** [comment] 2021-02-21 05:53
I would like to work on this in C++

**Comment by yashlikescode** [comment] 2021-02-22 02:19
If the problem is  about selecting string from a given array,
I can work on it using C,
I will pull request the same day issue is assigned

**Comment by abhinav5481** [comment] 2021-03-24 18:31
Hi @ankitapuri 
I would like to work on this issue using JavaScript. Please assign it to me

**Closed as completed** 2021-03-25 11:37 UTC
